package defpackage;

import com.umeng.commonsdk.debug.UMLogUtils;

/* compiled from: UMLogAnalytics */
/* renamed from: an */
public class an {
    public static final String O000000o;
    public static final String O00000Oo;
    public static final String O00000o;
    public static final String O00000o0;
    public static final String O00000oO;
    public static final String O00000oo;
    public static final String O0000O0o;
    public static final String O0000OOo;
    public static final String O0000Oo;
    public static final String O0000Oo0;
    public static final String O0000OoO;
    public static final String O0000Ooo;
    public static final String O0000o;
    public static final String O0000o0;
    public static final String O0000o00;
    public static final String O0000o0O;
    public static final String O0000o0o;
    public static final String O0000oO;
    public static final String O0000oO0;
    public static final String O0000oOO;
    public static final String O0000oOo;
    public static final String O0000oo;
    public static final String O0000oo0;
    public static final String O0000ooO;
    public static final String O0000ooo;
    public static final String O000O00o = "统计SDK常见问题索引贴 详见链接 http://developer.umeng.com/docs/66650/cate/66650";
    public static final String O000O0OO;
    public static final String O000O0Oo;
    public static final String O000O0o;
    public static final String O000O0o0;
    public static final String O000O0oO;
    public static final String O000O0oo;
    public static final String O000OO;
    public static final String O000OO00;
    public static final String O000OO0o;
    public static final String O000OOOo = "MobclickAgent.onDeepLinkReceived方法Context参数不能为null。|参数Context需要指定ApplicationContext值。";
    public static final String O000OOo = "MobclickAgent.onDeepLinkReceived方法link参数长度超过限制。|参数link长度不能超过1024字符。";
    public static final String O000OOo0 = "MobclickAgent.onDeepLinkReceived方法link参数不能为null，也不能为空字符串。|参数link必须为非空字符串。";
    public static final String O000OOoO;
    public static final String O000OOoo;
    public static final String O000Oo0;
    public static final String O000Oo00;
    public static final String O000Oo0O;
    public static final String O000Oo0o;
    public static final String O000OoO;
    public static final String O000OoO0;
    public static final String O000OoOO;
    public static final String O000OoOo;
    public static final String O000Ooo;
    public static final String O000Ooo0;
    public static final String O000OooO;
    public static final String O000Oooo;
    public static final String O000o;
    public static final String O000o0;
    public static final String O000o00;
    public static final String O000o000;
    public static final String O000o00O;
    public static final String O000o00o;
    public static final String O000o0O;
    public static final String O000o0O0;
    public static final String O000o0OO;
    public static final String O000o0Oo;
    public static final String O000o0o;
    public static final String O000o0o0;
    public static final String O000o0oo;
    public static final String O000oO;
    public static final String O000oO0;
    public static final String O000oO00;
    public static final String O000oO0O;
    public static final String O000oO0o;
    public static final String O000oOO;
    public static final String O000oOO0;
    public static final String O000oOOO;
    public static final String O000oOOo;
    public static final String O000oOo;
    public static final String O000oOo0;
    public static final String O000oOoO;
    public static final String O000oOoo;
    public static final String O000oo;
    public static final String O000oo0;
    public static final String O000oo0O;
    public static final String O000oo0o;
    public static final String O000ooO;
    public static final String O000ooO0;
    public static final String O000ooOO;
    public static final String O000ooOo;
    public static final String O000ooo;
    public static final String O000ooo0;
    public static final String O000oooO;
    public static final String O000oooo;
    public static final String O00O000o;
    public static final String O00O00Oo;
    public static final String O00O00o;
    public static final String O00O00o0;
    public static final String O00O0Oo;
    public static final String O00oOOoo;
    public static final String O00oOoOo;
    public static final String O00oOooO = "MobclickAgent.setSecret方法参数context不能为null|参数Context需要指定ApplicationContext值。";
    public static final String O00oOooo = "MobclickAgent.setSecret方法参数secretkey不能为null，也不能为空字符串。|secretkey参数必须是非空 字符串。";
    public static final String oooOoO;

    static {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合参数为空|onEvent接口必须传入非空的属性集合。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O000000o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件ID和保留字冲突|onEvent接口传入的事件ID不能和保留字冲突。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O00000Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件ID为null或者为空字符串|onEvent接口传入的事件ID不能为null，也不能为空字符串。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O00000o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合map没有加入K-V值|事件属性集合参数map必须添加K-V值。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O00000o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合map中key值和保留字冲突|事件属性集合map中key值不能和保留字冲突。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O00000oO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件ID为null或者长度超过限制|事件ID不能为null、空串，且长度不能超过128个字符。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O00000oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合参数为空或者事件属性集合map没有加入K-V值|事件属性集合参数map必须添加K-V值。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000O0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合map中key非法|事件属性集合参数map中key不能为非法的。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000OOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合map中value为null|事件属性集合参数map中value不能为null。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000Oo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件属性集合map中value长度超过限制|事件属性集合参数map中value如果为字符串时，其长度不能超过256个字符。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件标签为null或者为空字符串|onEvent接口传入的事件标签不能为null，也不能为空字符串。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000OoO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件ID为null或者长度超过限制，或事件标签长度超过限制|事件ID不能为null、空串，且长度不能超过128个字符。事件标签长度不能超过256个字符。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000Ooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("事件ID和保留字冲突|onEvent接口传入的事件ID不能和保留字冲突。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66946"));
        O0000o00 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onResume接口参数不能为null|MobclickAgent.onResume接口参数应该传入当前Activity的上下文。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onResume接口参数不是Activity的上下文|MobclickAgent.onResume接口参数应该传入当前Activity的上下文。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000o0O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onPause接口参数不能为null|MobclickAgent.onPause接口参数应该传入当前Activity的上下文。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000o0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onPause接口参数不是Activity的上下文|MobclickAgent.onPause接口参数应该传入当前Activity的上下文。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("@ 遗漏了Mobclick.onResume函数调用|每个Activity的onResume中都必须调用MobclickAgent.onResume。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000oO0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("@ 遗漏了Mobclick.onPaused函数调用|每个Activity的onPaused中都必须调用MobclickAgent.onPaused。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66948"));
        O0000oO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onProfileSignIn接口参数 账号ID 不能为null|账号ID不能为空。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66951"));
        O0000oOO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onProfileSignIn接口参数 账号ID 长度超过限制|账号ID 长度不能超过64个字符。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66951"));
        O0000oOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onProfileSignIn接口参数 账号来源 长度超过限制|账号来源 长度不能超过32个字符。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66951"));
        O0000oo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.reportError方法参数context不能为null|参数Context需要指定ApplicationContext值。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66971"));
        O0000oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.reportError方法参数error不能为null，也不能为空字符串。|error参数必须是非空字符串。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66971"));
        O0000ooO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.reportError方法 Context和Throwable参数都不能为空。|参数Context需要指定ApplicationContext值，Throwable参数传入捕获到的异常对象。详见问题链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66971"));
        O0000ooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onPageStart方法参数不能为null，也不能为空字符串。|参数viewName必须为非空字符串。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66975"));
        O000O0OO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("MobclickAgent.onPageEnd方法参数不能为null，也不能为空字符串。|参数viewName必须为非空 字符串。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66975"));
        O000O0Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("对于页面@，onPageStart和onPageEnd调用对的参数不一致。|对于同一个页面，请先调用onPageStart，再调用onPageEnd。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66975"));
        O00oOoOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("对于页面@，请确保先依序成对调用onPageStart，onPageEnd接口，再调用onPageStart接口对其它页面进行统计。|对于任意一个页面，必须依序成对调用onPageStart以及onPageEnd，不能有遗漏。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66975"));
        O000O0o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("对于页面@，请检查是否遗漏onPageStart接口调用。|对于任意一个页面，必须依序成对调用onPageStart以及onPageEnd，不能有遗漏。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66975"));
        O000O0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("当前发送策略为：启动时发送。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66976"));
        O000O0oO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("当前发送策略为: 间隔发送。间隔时间为：@秒。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66976"));
        O000O0oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("当前发送策略为: 集成测试。但是SDK未切换到调试模式，所以后台设置未生效。|如想切换到集成测试发送策略，请调用UMConfigure.setLogEnabled(true)将SDK切换到调试模式。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66976"));
        O000OO00 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("当前发送策略为：集成测试。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66976"));
        O000OO0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("当前发送策略为: 准实时发送。间隔时间为：@秒。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66976"));
        O000OO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("发送数据时发生java.net.UnknownHostException异常|友盟后端对设备端证书验证失败。请确保设备端没有运行抓包代理类程序。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66978"));
        O000OOoO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("发送数据时发生javax.net.sslHandshakeException异常|导致友盟后端域名解析失败。请检查系统DNS服务器配置是否正确。详见链接 ");
        stringBuilder.append(UMLogUtils.makeUrl("66978"));
        O000OOoo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("track接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Oo00 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("registerSuperProperty接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Oo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("unregisterSuperProperty接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Oo0O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("getSuperProperty接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接: ");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Oo0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("getSuperProperties接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000OoO0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("clearSuperProperties接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O00O0Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("setFirstLaunchEvent接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000OoO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("registerPreProperties接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000OoOO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("unregisterPreProperty接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000OoOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("clearPreProperties接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Ooo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("getPreProperties接口调用非法。|当前处于非DPLUS场景中，不能使用DPLUS相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67310"));
        O000Ooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("eventName为空，请检查|eventName参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67311"));
        O000OooO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("请注意：map为空|track接口的参数说明，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67311"));
        O000Oooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空｜context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67312"));
        O000o000 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("propertyName参数或propertyValue参数为空｜propertyName、propertyValue参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67312"));
        O000o00 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67313"));
        O000o00O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67316"));
        O000o00o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67318"));
        O000o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("trackID参数为空|trackID参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67318"));
        O000o0O0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67319"));
        O000o0O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("propertics参数为空|propertics参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67319"));
        O000o0OO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67320"));
        O000o0Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("未匹配到您传入的property参数|property参数不能匹配，");
        stringBuilder.append(UMLogUtils.makeUrl("67320"));
        O000o0o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67321"));
        O000o0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("context参数为空|context参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67322"));
        O000o0oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("startLevel接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("finishLevel接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oO00 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("failLevel接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oO0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("pay接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oO0O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("exchange接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oO0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("buy接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("use接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oOO0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("bonus接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oOO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("onAppResume接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oOOO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("onAppPause接口调用非法。|当前处于非Game场景中，不能使用Game相关接口，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67340"));
        O000oOOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数为空|level参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oOo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数超出64 chars|level参数不能超出64 chars，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数为空|level参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oOoO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数超出64 chars|level参数不能超出64 chars，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oOoo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数为空|level参数不能为空，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("level参数超出64 chars|level参数不能超出64 chars，详见问题连接：");
        stringBuilder.append(UMLogUtils.makeUrl("67341"));
        O000oo0O = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("money参数小于0或coin参数小于0|money参数不能小于0或coin参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67342"));
        O000oo0o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("source参数小于等于0或source参数大于等于100|source参数不能小于等于0或source参数不能大于等于100，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67342"));
        O000oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("source参数小于等于0或source参数大于等于100|source参数不能小于等于0或source参数不能大于等于100，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67342"));
        O000ooO0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("money参数小于0或number参数小于0或price参数小于0|money参数不能小于0或number参数不能小于0或price参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67342"));
        O000ooO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("item参数为空|item参数不能为空，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67342"));
        O000ooOO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("currencyAmount参数小于0或virtualAmount参数小于0|currencyAmount参数不能小于0或virtualAmount参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67343"));
        O000ooOo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("channel参数小于0或channel参数大于等于100|channel参数不能小于0或channel参数不能大于等于100，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67343"));
        O000ooo0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("item参数为空|item参数不能为空，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67344"));
        O000ooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("number参数小于0或price参数小于0|number参数不能小于0或price参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67344"));
        O000oooO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("coin参数小于0|coin参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67345"));
        O000oooo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("source参数小于0或source参数大于等于100|source参数不能小于0或source参数不能大于等于100，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67345"));
        oooOoO = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("item参数为空|item参数不能为空，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67345"));
        O00oOOoo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("number参数小于0或price参数小于0|number参数不能小于0或price参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67345"));
        O00O000o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("source参数小于0或source参数大于等于100|source参数不能小于0或source参数不能大于等于100，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67345"));
        O00O00Oo = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("item参数为空|item参数不能为空，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67346"));
        O00O00o0 = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("number参数小于0或price参数小于0|number参数不能小于0或price参数不能小于0，详见问题链接：");
        stringBuilder.append(UMLogUtils.makeUrl("67346"));
        O00O00o = stringBuilder.toString();
    }
}
